
CREATE TABLE ACCOUNTS (
    ACCOUNTID NUMBER PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50),
    ACCOUNTTYPE VARCHAR2(20),
    BALANCE NUMBER
);
INSERT INTO ACCOUNTS VALUES (101,'Deepa','SAVINGS',10000);
INSERT INTO ACCOUNTS VALUES (102,'Ravi','SAVINGS',15000);
INSERT INTO ACCOUNTS VALUES (103,'Priya','CURRENT',20000);

COMMIT;
--SELECT * FROM ACCOUNTS;
CREATE TABLE EMPLOYEES (
    EMPLOYEEID NUMBER PRIMARY KEY,
    EMPLOYEENAME VARCHAR2(50),
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER
);
INSERT INTO EMPLOYEES VALUES (1,'Arun','IT',50000);
INSERT INTO EMPLOYEES VALUES (2,'Kumar','HR',40000);
INSERT INTO EMPLOYEES VALUES (3,'Meena','IT',60000);

COMMIT;
--SELECT * FROM EMPLOYEES;
/* Scenario 1 */

CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest
AS
BEGIN
   UPDATE ACCOUNTS
   SET BALANCE = BALANCE + (BALANCE * 0.01)
   WHERE ACCOUNTTYPE = 'SAVINGS';

   COMMIT;

   DBMS_OUTPUT.PUT_LINE('Monthly Interest Applied Successfully');
END;
/

/* Scenario 2 */

CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(
   p_department IN VARCHAR2,
   p_bonus_percent IN NUMBER
)
AS
BEGIN
   UPDATE EMPLOYEES
   SET SALARY = SALARY + (SALARY * p_bonus_percent / 100)
   WHERE DEPARTMENT = p_department;

   COMMIT;

   DBMS_OUTPUT.PUT_LINE('Employee Bonus Updated Successfully');
END;
/

/* Scenario 3*/

CREATE OR REPLACE PROCEDURE TransferFunds(
   p_from_account IN NUMBER,
   p_to_account IN NUMBER,
   p_amount IN NUMBER
)
AS
   v_balance NUMBER;
BEGIN
   SELECT BALANCE
   INTO v_balance
   FROM ACCOUNTS
   WHERE ACCOUNTID = p_from_account;

   IF v_balance >= p_amount THEN

      UPDATE ACCOUNTS
      SET BALANCE = BALANCE - p_amount
      WHERE ACCOUNTID = p_from_account;

      UPDATE ACCOUNTS
      SET BALANCE = BALANCE + p_amount
      WHERE ACCOUNTID = p_to_account;

      COMMIT;

      DBMS_OUTPUT.PUT_LINE('Transfer Successful');

   ELSE

      DBMS_OUTPUT.PUT_LINE('Insufficient Balance');

   END IF;
END;
/

SET SERVEROUTPUT ON;

EXEC ProcessMonthlyInterest;

EXEC UpdateEmployeeBonus('IT',10);

EXEC TransferFunds(101,102,2000);
SELECT *FROM ACCOUNTS;
--SELECT *FROM EMPLOYEES;